const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Shirt 1',
      tag: 'nike-shirt-1',
      category: 'tops',
      image: '/images/p1.jpg', //679px x 829px
      price: 500,
      countInStock: 0,
      brand: 'Nike',
      rating: 1.2,
      numReviews: 10,
      description: 'hulaan mo 1',
    },
    {
      _id: '2',
      name: 'Nike Shirt 2',
      tag: 'nike-shirt-2',
      category: 'tops',
      image: '/images/p2.jpg',
      price: 211,
      countInStock: 20,
      brand: 'Nike',
      rating: 1.5,
      numReviews: 12,
      description: 'hulaan mo 2',
    },
    {
      _id: '3',
      name: 'Nike Shirt 3',
      tag: 'nike-shirt-3',
      category: 'tops',
      image: '/images/p3.jpg',
      price: 304,
      countInStock: 20,
      brand: 'Nike',
      rating: 5.6,
      numReviews: 19,
      description: 'hulaan mo 3',
    },
    {
      _id: '4',
      name: 'Nike Pants 1',
      tag: 'nike-pants-1',
      category: 'tops',
      image: '/images/pt1.jpg',
      price: 220,
      countInStock: 20,
      brand: 'Nike',
      rating: 9,
      numReviews: 30,
      description: 'hulaan mo Pants 1',
    },
    {
      _id: '4',
      name: 'Nike Pants 2',
      tag: 'nike-pants-2',
      category: 'tops',
      image: '/images/pt2.jpg',
      price: 500,
      countInStock: 20,
      brand: 'Nike',
      rating: 6.2,
      numReviews: 130,
      description: 'hulaan mo Pants 2',
    },
    {
      _id: '5',
      name: 'Nike Pants 3',
      tag: 'nike-pants-3',
      category: 'tops',
      image: '/images/pt3.jpg',
      price: 250,
      countInStock: 100,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 200,
      description: 'hulaan mo Pants 3',
    },
  ],
};

export default data;
